/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class indi_blazing_stellar_jni_TDOMEncryptOrDecryptFileReborn_StateDataWorker */

#ifndef _Included_indi_blazing_stellar_jni_TDOMEncryptOrDecryptFileReborn_StateDataWorker
#define _Included_indi_blazing_stellar_jni_TDOMEncryptOrDecryptFileReborn_StateDataWorker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     indi_blazing_stellar_jni_TDOMEncryptOrDecryptFileReborn_StateDataWorker
 * Method:    getNewObjectPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_indi_blazing_stellar_jni_TDOMEncryptOrDecryptFileReborn_StateDataWorker_getNewObjectPointer
  (JNIEnv *, jclass);

/*
 * Class:     indi_blazing_stellar_jni_TDOMEncryptOrDecryptFileReborn_StateDataWorker
 * Method:    encrypter
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_indi_blazing_stellar_jni_TDOMEncryptOrDecryptFileReborn_StateDataWorker_encrypter
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     indi_blazing_stellar_jni_TDOMEncryptOrDecryptFileReborn_StateDataWorker
 * Method:    decrypter
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_indi_blazing_stellar_jni_TDOMEncryptOrDecryptFileReborn_StateDataWorker_decrypter
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     indi_blazing_stellar_jni_TDOMEncryptOrDecryptFileReborn_StateDataWorker
 * Method:    encrypterWithoutPadding
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_indi_blazing_stellar_jni_TDOMEncryptOrDecryptFileReborn_StateDataWorker_encrypterWithoutPadding
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     indi_blazing_stellar_jni_TDOMEncryptOrDecryptFileReborn_StateDataWorker
 * Method:    decrypterWithoutUnpadding
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_indi_blazing_stellar_jni_TDOMEncryptOrDecryptFileReborn_StateDataWorker_decrypterWithoutUnpadding
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     indi_blazing_stellar_jni_TDOMEncryptOrDecryptFileReborn_StateDataWorker
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_indi_blazing_stellar_jni_TDOMEncryptOrDecryptFileReborn_StateDataWorker_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
